export const ActionTypes = {
  FETCH_DATA_START: "FETCH_DATA_START",
  GET_ALL_COUNTRIES: "GET_ALL_COUNTRIES",
  GET_ALL_COUNTRIES_ERROR: "GET_ALL_COUNTRIES_ERROR",
  GET_COUNTRIES_DETAILS: "GET_COUNTRIES_DETAILS",
  GET_COUNTRIES_DETAILS_ERROR: "GET_COUNTRIES_DETAILS_ERROR",
  COUNTRY_INPUT: "COUNTRY_INPUT",
};
